module.exports = [['Stuhl', 'Sessel', 'Hocker', 'Tisch'],
['Auto', 'Fahrrad', 'Motorrad', 'Bus'],
['Marmor (Stein)', 'Kachel (Stein)', 'Ziegel (Stein)', 'Granit (Stein)'],
['Schwein', 'Kuh', 'Ochse', 'Ziege'],
['Ziege', 'Steinbock', 'Widder', 'Hirsch'],
['Hirsch', 'Elch', 'Reh', 'Wildschwein'],
['Hund', 'Katze', 'Hamster', 'Meerschweinchen'],
['Planet', 'Stern', 'Sonne', 'Mond', 'Komet'],
['Maurer', 'Schreiner', 'Maler', 'Klempner'],
['Bauer', 'Bäcker', 'Konditor', 'Metzger'],
['U-Bahn', 'Zug', 'Strassenbahn', 'Bus'],
['Toilette', 'Waschbecken', 'Dusche', 'Badewanne'],
['Handtuch', 'Waschlappen', 'Schwamm', 'Küchentuch'],
['Achterbahn', 'Autoscooter', 'Geisterbahn', 'Kettenkarussel'],
['Holiday Park', 'Europa Park', 'Tripsdrill', 'Legoland'],
['Tennis', 'Tischtennis', 'Squash', 'Badminton'],
['Fussball', 'Handball', 'Eishockey', 'Volleyball'],
['Gewitter', 'Sturm', 'Hagel', 'Schnee'],
['See', 'Fluss', 'Meer', 'Teich'],
['Moderator', 'Journalist', 'Redakteur', 'Kameramann'],
['Schauspieler', 'Regisseur', 'Stuntman', 'Statist (Film)'],
['Archäologe', 'Historiker', 'Geologe', 'Biologe'],
['Biologe', 'Chemiker', 'Physiker', 'Mediziner'],
['Master', 'Magister', 'Bachelor', 'Doktor'],
['Hamburger', 'Frankfurter', 'Wiener', 'Nürnberger'],
['Grill', 'Herd', 'Backofen', 'Mikrowelle'],
['Kochtopf', 'Pfanne', 'Wok', 'Deckel'],
['Messer', 'Gabel', 'Löffel', 'Schere'],
['Wandern', 'Spazieren', 'Bergsteigen', 'Joggen'],
['Gabelstapler', 'Bagger', 'Kran', 'Dampfwalze'],
['Kerze', 'Lampe', 'Feuerzeug', 'Lagerfeuer'],
['Wachs', 'Öl', 'Fett', 'Silikon'],
['Wespe', 'Biene', 'Hummel', 'Hornisse'],
['Giraffe', 'Elefant', 'Nilpferd', 'Nashorn'],
['Löwe', 'Tiger', 'Leopard', 'Puma'],
['Hai', 'Wal', 'Delfin', 'Seelöwe'],
['Pinguin', 'Eisbär', 'Seelöwe', 'Walross'],
['Biber', 'Waschbär', 'Otter', 'Dachs'],
['Rose', 'Tulpe', 'Hibiskus', 'Orchidee'],
['Erdbeere', 'Himbeere', 'Brombeere', 'Johannisbeere'],
['Schweden', 'Finnland', 'Norwegen', 'Dänemark'],
['Karamell', 'Zucker', 'Honig', 'Schokolade'],
['Schokolade', 'Bonbon', 'Kaugummi', 'Lutscher'],
['Hawaii', 'Malediven', 'Fidschi', 'Seychellen'],
['Kobold', 'Troll', 'Klabautermann', 'Pumuckl'],
['Porsche', 'Ferrari', 'Lamborghini', 'Bugatti'],
['Fee', 'Hexe', 'Elf', 'Flaschengeist'],
['Glas', 'Tasse', 'Becher', 'Krug'],
['Hammer', 'Zange', 'Schraubenzieher', 'Säge'],
['Marmelade', 'Honig', 'Nutella', 'Gelee'],
['Kapern', 'Oliven', 'Essiggurken', 'Kimchi'],
['Karotte', 'Pastinake', 'Kartoffel', 'Rettich'],
['Buch', 'Zeitung', 'Magazin', 'Comic'],
['Skifahren', 'Langlauf', 'Snowboard', 'Schlittenfahren'],
['Schach', 'Dame (Spiel)', 'Go (Spiel)', 'Mühle (Spiel)'],
['Chili', 'Wasabi', 'Meerrettich', 'Pfeffer'],
['Thomas Müller', 'Miroslav Klose', 'Philipp Lahm', 'Bastian Schweinsteiger'],
['Weihnachten', 'Neujahr', 'Ostern', 'Mittsommerfest'],
['Orange', 'Mandarine', 'Zitrone', 'Grapefruit'],
['Bart', 'Augenbraue', 'Wimper', 'Achselhaare'],
['Brille', 'Kontaktlinse', 'Lupe', 'Monokel'],
['Shampoo', 'Duschgel', 'Seife', 'Spülmittel'],
['Kakao', 'Latte Machiato', 'Cappuccino', 'Espresso'],
['Popeye', 'Asterix', 'Gummibären'],
['Tom & Jerry', 'Sylvester & Tweety', 'Road Runner & Coyote', 'Speedy Gonzales & Sylvester'],
['Donald Duck', 'Asterix', 'Micky Maus', 'Lucky Luke'],
['Audi', 'BMW', 'Mercedes', 'Volkswagen'],
['Adam und Eva', 'Bonnie und Clyde', 'Romeo und Julia', 'Othello und Desdemona'],
['Babyloner', 'Griechen', 'Azteken', 'Mayas', 'Ägypter'],
['Robin Hood', 'Batman', 'Superman', 'Spiderman'],
['Siegfried', 'Achilles', 'Herakles', 'Thor'],
['Asterix', 'Obelix', 'Miraculix', 'Majestix'],
['Iron Man', 'Thor', 'Hulk', 'Spider Man', 'Captain America'],
['Simpsons', 'Latte Machiato', 'Cappuccino'],
['Mogli', 'Aladin', 'Pinocchio', 'Peter Pan', 'Tarzan'],
['Mulan', 'Arielle die Meerjungfrau', 'Pocahontas', 'Alice im Wunderland'],
['Bambi', 'Dumbo', 'König der Löwen'],
['Wein', 'Schnaps', 'Bier', 'Likör'],
['Wein', 'Sekt', 'Champagner'],
['Zeugen Jehovas', 'Scientology', 'Mormonen', 'Hare Krishna'],
['SPD', 'AfD', 'CDU', 'Die Grünen', 'FDP', 'Linkspartei'],
['Kim Jong Un', 'Donald Trump', 'Wladimir Putin', 'Recep Tayyip Erdogan', 'Jair Bolsonaro', 'Boris Johnson'],
['Wladimir Putin', 'Michail Gorbatschow', 'Boris Jelzin', 'Dmitri Medwedew'],
['Da Vinci', 'Michelangelo', 'Van Gogh', 'Picasso'],
['Wolfgang Amadeus Mozart', 'Johann Sebastian Bach', 'Ludwig van Beethoven', 'Richard Wagner'],
['Carl Friedrich Gauss', 'Leonhard Euler', 'Gottfried Wilhelm Leibniz', 'David Hilbert'],
['Isaac Newton', 'Albert Einstein', 'Max Planck', 'Stephen Hawking'],
['Euklid', 'Pythagoras', 'Archimedes', 'Eratostenes'],
['Mariah Carey', 'Whitney Houston', 'Tina Turner', 'Céline Dion'],
['Beatles', 'Rolling Stones', 'Queen', 'Abba'],
['Masern', 'Scharlach', 'Röteln', 'Windpocken'],
['Singapur', 'Hongkong', 'Bangkok', 'Tokyo', 'Seoul'],
['Knoblauch', 'Frühlingszwiebel', 'Schnittlauch', 'Schalotte'],
['Hokkaido', 'Butternut', 'Muskat (Kürbis)', 'Zucchini'],
['Honigmelone', 'Wassermelone', 'Galiomelone', 'Cantaloupe (Melone)'],
['Chips', 'Salzstangen', 'Erdnüsse', 'Salzbrezeln'],
['Mais', 'Hirse', 'Weizen', 'Reis', 'Hafer'],
['Orang Utan', 'Schimpanse', 'Gorilla', 'Pavian'],
['Matterhorn', 'Montblanc', 'Zugspitze', 'Großglockner'],
['Banane', 'Mango', 'Ananas', 'Papaya'],
['Nelke', 'Veilchen', 'Lavendel'],    
['Ford', 'Chrysler', 'Chevrolet'],
['Feige', 'Dattel', 'Mango', 'Litschi'],
['Koralle', 'Muschel', 'Seegurke', 'Seestern'],
['Sternfrucht', 'Guave', 'Drachenfrucht', 'Passionsfrucht'],
['Drache', 'Phoenix', 'Einhorn', 'Yeti'],
['Zombie', 'Werwolf', 'Vampir', 'Waldgeist'],
['Chamäleon', 'Eidechse', 'Salamander', 'Gekko'],
['Dinosaurier', 'Mammut', 'Säbelzahntiger', 'Neanderthaler'],
['Tyrannosaurus', 'Velociraptor', 'Brontosaurus', 'Stegosaurus', 'Triceratops', 'Diplodocus'],
['Kaktus', 'Agave', 'Akazie'],
['Rosmarin', 'Salbei', 'Basilikum', 'Thymian'],
['Sandalen', 'Gummistiefel', 'Hausschuhe', 'Turnschuhe'],
['Jacke', 'Unterhemd', 'T-Shirt', 'Pullover'],
['Shorts', 'Unterhose', 'Badehose', 'Radlerhose'],
['Döner', 'Hamburger', 'Hot Dog'],
['Nil', 'Amazonas', 'Yangtse', 'Mississippi'],
['Pferd', 'Esel', 'Pony', 'Maultier'],
['Kamel', 'Dromedar', 'Lama', 'Alpaka'],
['Hillary Clinton', 'Theresa May', 'Ursula von der Leyen', 'Angela Merkel'],
['Fenster', 'Haustür', 'Balkontür', 'Gartentür'],
['Terasse', 'Pagode', 'Balkon', 'Wintergarten'],
['Tanne', 'Eiche', 'Ahorn', 'Birke'],
['Apfel', 'Birne', 'Quitte', 'Pflaume'],
['Rhein', 'Mosel', 'Elbe', 'Donau'],
['Snowboard', 'Skateboard', 'Surfboard', 'Wakeboard'],
['Gran Canaria', 'Ibiza', 'Teneriffa', 'Mallorca'],
['Rotkäppchen', 'Schneewittchen', 'Aschenputtel', 'Rapunzel', 'Dornröschen'],
['Pfirsich', 'Aprikose', 'Mirabelle', 'Nektarine'],
['Orthopäde', 'Chirug', 'Anästhäsist', 'Physiotherapeut'],
['Rosmarin', 'Salbei', 'Basilikum', 'Thymian'],
['Verlobung', 'Taufe', 'Geburtstag', 'Hochzeit'],
['Venus', 'Jupiter', 'Mars', 'Saturn', 'Uranus'],
['Elba', 'Sardinien', 'Sizilien', 'Zypern'],
['Wolf und die Sieben Geißlein', 'Bremer Stadtmusikanten', 'Hase und Igel', 'Reineke Fuchs'],
['Ecuador', 'Costa Rica', 'Panama', 'Nicaragua'],
['Melone', 'Melonenkern', 'Melonenschale', 'Melonenfruchtfleisch'],
['Aldi', 'Lidl', 'Rewe', 'Kaufland', 'Edeka'],
['Kirsche', 'Kirschkern', 'Kirschbaum', 'Kirschbaumblatt'],
['Schwan', 'Ente', 'Gans', 'Pelikan'],
['Stockholm', 'Oslo', 'Kopenhagen', 'Helsinki'],
['Schneekette', 'Lichterkette', 'Menschenkette', 'Wortkette']
['Nassrasierer', 'Rasierklinge', 'Elektrorasierer', 'Rasierschaum'],
['Regen', 'Schnee', 'Hagel', 'Wind'],
['Wolle', 'Seide', 'Nylon', 'Polyester'],
['Käse', 'Joghurt', 'Quark', 'Sahne'],
['Aktie', 'Fonds', 'Sparbuch', 'Optionsschein'],
['Osterhase', 'Weihnachtsmann', 'Nikolaus', 'Christkind'],
['Schrank', 'Regal', 'Kommode', 'Nachttisch'],
['Rapsöl', 'Sonnenblumenöl', 'Sesamöl', 'Sojaöl', 'Olivenöl', 'Erdnussöl'],
['Handcreme', 'Sonnencreme', 'Gesichtscreme', 'Wundcreme'],
['Kühlschrank', 'Tiefkühlfach', 'Tiefkühltruhe', 'Kühltruhe'],
['Atom', 'Elektron', 'Molekül', 'Proton', 'Photon'],
['Sojabohne', 'Kidneybohne', 'Princessbohne', 'Mungobohne'],
['Bill Gates', 'Jeff Bezos', 'Tim Cook', 'Steve Jobs', 'Satya Nadella', 'Larry Page'],
['Bleistift', 'Kugelschreiber', 'Filzstift', 'Füller'],
['Nest', 'Höhle', 'Stall', 'Hundehütte'],
['Cousine', 'Schwiegermutter', 'Tante', 'Nichte'],
['Klettern', 'Hüpfen', 'Strampeln', 'Kriechen'],
['Girlande', 'Lametta', 'Konfetti', 'Luftschlange'],
['Ziffer', 'Buchstabe', 'Symbol', 'Note'],
['Bargeld', 'Scheck', 'Überweisung', 'Kreditkarte'],
['Entführen', 'Betrügen', 'Überfallen', 'Ausrauben'],
['Neidhammel', 'Pechvogel', 'Faulpelz', 'Heulsuse'],
['Popcorn', 'Zuckerwatte', 'Puffreis', 'Waffeln'],
['Kniebeugen', 'Klimmzüge', 'Liegestütze', 'Sit-ups'],
['Spülmaschine', 'Staubsauger', 'Kehrmaschine', 'Waschmaschine'],
['Fernseher', 'Laptop', 'Computter', 'Tablet'],
['Hufe', 'Zehen', 'Flossen', 'Pfote', 'Krallen'],
['Kilogramm', 'Pfund', 'Zentner', 'Unze'],
['Kelvin', 'Celsius', 'Fahrenheit'],
['Inch', 'Yard', 'Foot', 'Mile'],
['Walnuss', 'Erdnuss', 'Haselnuss', 'Mandel', 'Pistazie'],
['Yoga', 'Tai Chi', 'Pilates'],
['Haut', 'Fell', 'Schuppen', 'Federn'],
['Speicher', 'Keller', 'Garage', 'Abstellkammer'],
['Schulter', 'Ellbogen', 'Knie', 'Hüfte'],
['Knolle', 'Stengel', 'Stamm', 'Wurzel', 'Ast', 'Blatt', 'Knospe', 'Blüte'],
['Strasse', 'Radweg', 'Fußgängerzone', 'Zebrastreifen'],
['Zebrastreifen', 'Ampel', 'Kreisverkehr', 'Überführung', 'Unterführung'],
['Schmelzen', 'Dämpfen', 'Schwitzen', 'Kochen', 'Fritieren'],
['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
['Socke', 'Mütze', 'Handschuhe', 'Schal'],
['Wippe', 'Rutsche', 'Schaukel', 'Kreisel'],
['Sicherheitsnadel', 'Nähnadel', 'Zahnstocher', 'Stricknadel', 'Impfnadel', 'Reißzwecke'],
['Clown', 'Feuerschlucker', 'Dompteur', 'Seiltänzer', 'Jongleur'],
['Lied', 'Märchen', 'Gedicht', 'Roman'],
['Gitarre', 'Geige', 'Cello', 'Kontrabass', 'Harfe', 'Violine'],
['Trommel', 'Becken', 'Xylophon'],
['Karosserie', 'Motorhaube', 'Kofferraum', 'Reifen'],
['Bank', 'Post', 'Apotheke', 'Rathaus'],
['Landkarte', 'Geburtstagskarte', 'Eintrittskarte', 'Postkarte'],
['Schlitten', 'Ski', 'Schlittschuhe', 'Snowboard'],
['Schaufel', 'Besen', 'Rechen', 'Spaten'],
['Ringfinger', 'Zeigefinger', 'Mittelfinger', 'Daumen'],
['Platin', 'Silber', 'Gold', 'Bronze', 'Eisen'],
['Bernstein', 'Jade', 'Diamant', 'Saphir', 'Rubin'],
['Esszimmer', 'Schlafzimmer', 'Badezimmer', 'Wohnzimmer'],
['Teig', 'Gummi', 'Knete', 'Silikon'],
['Skispringen', 'Biathlon', 'Slalom', 'Bobfahren']
];
